### ISSUE TITLE
My discord was compromised from a bad link

### ISSUE THREAD

**Issue by graygxxsx** [jcsumlin/discord-ban-appeal#58]
i put in a request before but still have not heard nothing. I just tried to put in another and it would not go through. 

Display name: G$

Username: gxxsx

**Comment by MrFoxyOfficial** [comment]
Making more of them, is pointless, because the developer of this app can't do anything. He can't unban you as he doesn't have access. 

ZKSYNC server or whatever it is, didn't fully configured the application and therefor, it's showing you this link. Your best way to reach out would be through social media.
